import type { Metadata } from "next";
import { AppProviders } from "@/components/common/app-providers";
import { Toaster } from "@/components/ui/sonner";
import { geistMono, geistSans } from "@/fonts";
import type { LayoutProps } from "@/types/common";

import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js Template",
    template: "%s ‹ Template",
  },
  description: "Generated by create next app",
  authors: [
    {
      name: "Vinicius Fernandes",
      url: "https://github.com/fernandes-vinicius",
    },
  ],
  twitter: {},
  robots: "index, follow",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
          <Toaster richColors />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
